import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import githubLogo from "../public/github-logo.svg";
import linkedIn from "../public/linkedin-logo.svg";

export default function Home() {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Yebin's Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className={styles.header}>
        <div className={styles.headerNav}>
          <div className={styles.logoGroup}>
            <div className={styles.logo}>YC</div>
            <div className={styles.logoDot}>.</div>
          </div>
          <div className={styles.navContact}>
            <div>Contact me</div>
            <a href="https://github.com/Yebincho03">
              <Image src={githubLogo} alt="githubLogo" />
            </a>
            <a href="https://www.linkedin.com/in/yebincho">
              <Image src={linkedIn} alt="linkedInLogo" />
            </a>
          </div>
        </div>
      </div>
      <div className={styles.body}>
        <div className={styles.home}>
          <div>HI THERE 👋</div>
          <div className={styles.title}>I'm Yebin</div>
          <div className={styles.title}>Front-end developer</div>
        </div>
      </div>
    </div>
  );
}
