import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Project from "../components/Project";
import Hero from "../components/Hero";
import styled from "styled-components";
import About from "../components/About";
import styles from "../styles/Home.module.css";
import { globalColor } from "../shared/Style";
import ProjectsContainer from "../components/ProjectsContainer";

export default function Home() {
  return (
    <Contanier>
      <Head>
        <title>Yebin's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <Hero />
        <About />
        <ProjectsContainer />
      </Wrapper>
    </Contanier>
  );
}

const Contanier = styled.div`
  margin: 0;
  padding: 0;
`;

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin: 0;
  padding: 0;
  background-color: ${globalColor.grey100};
  color: ${globalColor.grey0};
`;
