import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import githubLogo from "../public/github-logo.svg";
import linkedIn from "../public/linkedin-logo.svg";

export default function Home() {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Yebin's Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className={styles.body}>
        <div className={styles.home}>
          <div>HI THERE 👋</div>
          <div className={styles.title}>I'm Yebin</div>
          <div className={styles.title}>Front-end developer</div>
        </div>
      </div>
    </div>
  );
}
